server:
  # 端口
  port: 8080


spring:
  # 数据源配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://<your-ip>/<your-database>?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2b8
    username: <your-username>
    password: <your-password>
    hikari:
      connection-test-query: SELECT 1 # 自动检测连接
      connection-timeout: 60000 #数据库连接超时时间,默认30秒
      idle-timeout: 500000 #空闲连接存活最大时间，默认600000（10分钟）
      max-lifetime: 540000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      maximum-pool-size: 30 #连接池最大连接数，默认是10
      minimum-idle: 10 #最小空闲连接数量
      pool-name: SPHHikariPool # 连接池名称
  # 配置序列化时的时间格式和时区
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 配置redis
  data:
    redis:
      host: <your-database>
      port: 6379
      database: 0


mybatis-plus:
  #用于打印框架生成的sql语句，便于调试
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


minio:
  endpoint: http://<your-endpoint>
  access-key: <your-key>
  secret-key: <your-value>
  bucket-name: lease


springdoc:
  # queryVo参数不方便调试，将queryVo做打平处理。
  default-flat-param-object: true